### ISSUE TITLE
Function `fit( )` not used

### ISSUE THREAD

**Issue by ctroupin** [gher-uliege/DIVAnd.jl#108]
Might be wrong but it seems the function `fit()` defined here:
https://github.com/gher-uliege/DIVAnd.jl/blob/master/src/fit.jl#L412
is not used in the code

**Comment by Alexander-Barth** [comment]
Indeed, the function `fit` is not used because the functions `fithorzlen` and `fitvertlen` generally work better. So far, I did not removed this function because it might break other users code and maybe someday a way is found to improve them.

If this function fit cause confusion, maybe we should remove it as mentioned here:
https://gher-uliege.github.io/DIVAnd.jl/latest/#API-changes

**Comment by ctroupin** [comment]
Thanks Alex,
it probably makes sense to keep it then. 
It caused me a bit (not a lot) of confusion while trying to reply to a user email about how the fit was working, but now it's clear!

**Comment by Alexander-Barth** [comment]
Would it help if we put them in a file called deprecated.jl ? (they would be still available but it would be clearer that they are not used)

**Comment by ctroupin** [comment]
Sure, that can be a clean way to do it. Or even if we write "deprecated" before the function definition in the source code can help when one has to dig into the code.
