### ISSUE TITLE
[👆] Getting lists of data points that are used for each depth layer

### ISSUE THREAD

**Issue by ctroupin** [gher-uliege/DIVAnd.jl#118]
**Describe your objective**

Users would like to know which data points are used for an interpolation on a given layer, for instance winter at 500 m depth, knowing the vertical correlation length.

**Explain why it is not currently possible to do it?**

I guess in the loop it would be a matter of writing files (such as the ones written by `saveobs`) storing all the obs. 

**[Optional] Describe how you would solve that**

Also would be nice to have an illustration of the vertical correlation length (in a notebook for example) because it seems to cause confusion with several users. For instance, if one increases the vertical correlation length, is it expected to get more or less variability.

**Comment by jmbeckers** [comment]
If the direct solver is used, ALL data points are used though only those within the reach of the length scales have a significant impact.

If you use diva3d with vertical tiling, then of course you limit the data to those within the vertical window

In principle, increasing L filters more and reduces variability for homogenous data coverage . But maybe with a lot of data near the surface and only a few in deep layers, increasing Lv could actually increase variability because you extrapolate more.

**Comment by ctroupin** [comment]
yes that's what I was thinking about the influence of `Lv`, maybe in some cases it can increase variability.

Also for the data used I think there might have been a confusion (now solved) with the parameter `searchz` (used in the fitting) but not in the interpolation/analysis
